# Generated by Django 5.1.4 on 2024-12-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
