# Generated by Django 5.1.4 on 2024-12-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permissions',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
