# Generated by Django 5.1.4 on 2024-12-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
