# Generated by Django 5.1.4 on 2024-12-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='permissions',
        ),
    ]
