# Generated by Django 5.1.4 on 2024-12-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
