# Generated by Django 5.1.4 on 2024-12-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
