# Generated by Django 5.1.4 on 2024-12-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_title_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
