# Generated by Django 5.1.4 on 2024-12-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
