# Generated by Django 5.1.4 on 2024-12-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='availableColors',
        ),
    ]
