# Generated by Django 5.1.4 on 2024-12-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_subcategory_product_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategories',
        ),
    ]
