# Generated by Django 5.1.4 on 2024-12-25 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_subcategory_product_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
    ]
