# Generated by Django 5.1.4 on 2024-12-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_product_subcategory_product_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratingsQuantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
