# Generated by Django 5.1.4 on 2024-12-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availableColors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
